syntax = "proto3";

// Bu servis ismi Python tarafındaki sınıf ismini (PricePredictorServicer) belirler.
service PricePredictor {
  rpc PredictPrice (PredictionRequest) returns (PredictionResponse);
}

// Node.js'ten Python'a gönderilecek veriler (Veri setinizdeki sütunlar)
message PredictionRequest {
  int32 segment = 1;
  int32 seri_no = 2;
  int32 ram_gb = 3;
  int32 kamera_mp = 4;
  int32 ekran_boyutu = 5;
  int32 batarya_mah = 6;
  int32 storage_gb = 7;
  int32 cihaz_durum = 8;
  int32 cikis_yili = 9;
}

// Python'dan Node.js'e dönecek fiyat tahmini
message PredictionResponse {
  float predicted_price = 1;
}